"""Reproduce all computational evidence for the five assignment stages.

GUI evidence is generated by capture_gui.py.  Interoperability with another
student group needs that group's actual exported results; the two independent
local implementations here are explicitly labelled internal cross-checks.
"""

from __future__ import annotations

import argparse
import csv
from datetime import datetime
import hashlib
import io
import json
from pathlib import Path
import platform
import sys
from time import perf_counter
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import analysis_tools
import reference_sdes as reference
import sdes

SCHEDULES = ("assignment", "cumulative")
KEY = 0b1010000010
PLAIN = 0b10011010
# Literals checked by hand, and then by the independent string implementation.
HAND = {
    "assignment": {"k1": "10100100", "k2": "10010010", "ciphertext": "11101111",
                   "round2_xor": "00101100", "round2_sboxes": "0001", "round2_p4": "0100", "round2": "11110111"},
    "cumulative": {"k1": "10100100", "k2": "01000011", "ciphertext": "01101011",
                   "round2_xor": "11111101", "round2_sboxes": "1000", "round2_p4": "0001", "round2": "10100111"},
}


def timestamp():
    return datetime.now().astimezone().isoformat(timespec="milliseconds")


def write_json(path, data):
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run_tests(out):
    suite = unittest.defaultTestLoader.discover(str(ROOT / "tests"), top_level_dir=str(ROOT))
    def names_in(collection):
        names = []
        for item in collection:
            names.extend(names_in(item) if isinstance(item, unittest.TestSuite) else [item.id()])
        return names
    test_names = names_in(suite)
    log = io.StringIO()
    started_at = timestamp()
    start = perf_counter()
    result = unittest.TextTestRunner(stream=log, verbosity=2).run(suite)
    elapsed = perf_counter() - start
    (out / "unit_tests.txt").write_text(log.getvalue(), encoding="utf-8")
    summary = {
        "started_at": started_at, "finished_at": timestamp(), "elapsed_seconds": elapsed,
        "tests_run": result.testsRun, "failures": len(result.failures), "errors": len(result.errors),
        "skipped": len(result.skipped), "successful": result.wasSuccessful(),
        "test_names": test_names,
        "failed_or_error_test_names": [test.id() for test, _ in result.failures + result.errors],
        "exhaustive_test": "tests.test_sdes.ExhaustiveDomainTests.test_both_schedules_all_keys_all_blocks_and_bijections",
        "assignment_encryptions_compared": 1024 * 256,
        "assignment_core_round_trips": 1024 * 256,
        "assignment_reference_round_trips": 1024 * 256,
        "assignment_bijections_verified": 1024,
        "cumulative_encryptions_compared": 1024 * 256,
        "cumulative_core_round_trips": 1024 * 256,
        "cumulative_reference_round_trips": 1024 * 256,
        "cumulative_bijections_verified": 1024,
        "cumulative_additional_sample_encryptions_compared": 1024 * 16,
        "total_exhaustive_encryptions_compared": 2 * 1024 * 256,
        "total_exhaustive_core_round_trips": 2 * 1024 * 256,
        "total_exhaustive_reference_round_trips": 2 * 1024 * 256,
        "total_bijections_verified": 2 * 1024,
        "subkey_pairs_compared_each_schedule": 1024,
    }
    write_json(out / "unit_tests.json", summary)
    print(f"unittest: {result.testsRun} tests, success={result.wasSuccessful()}, {elapsed:.6f}s", flush=True)
    if not result.wasSuccessful():
        print(log.getvalue(), file=sys.stderr)
        raise RuntimeError("Validation failed; see results/unit_tests.txt")
    return summary


def hand_vectors(out):
    vectors = []
    for schedule in SCHEDULES:
        expected = HAND[schedule]
        assert reference.generate_subkeys_bits(f"{KEY:010b}", schedule) == (expected["k1"], expected["k2"])
        assert reference.encrypt_bits(f"{PLAIN:08b}", f"{KEY:010b}", schedule) == expected["ciphertext"]
        assert sdes.encrypt_block(PLAIN, KEY, schedule) == int(expected["ciphertext"], 2)
        vectors.append({
            "schedule": schedule, "key": "1010000010", "plaintext": "10011010", **expected,
            "p10": "1000001100", "p10_left": "10000", "p10_right": "01100",
            "shift1": "0000111000", "shift2_total": "0001010001" if schedule == "assignment" else "0010000011",
            "ip": "00011011", "round1_ep": "11010111", "round1_xor": "01110011",
            "round1_sboxes": "0011", "round1_p4": "0110", "round1": "01111011", "swap": "10110111",
            "round2_ep": "10111110", "core_trace": sdes.trace_block(PLAIN, KEY, schedule=schedule),
            "reference_trace": reference.trace_bits(f"{PLAIN:08b}", f"{KEY:010b}", schedule),
        })
    data = {
        "provenance": "Fixed literals derived by hand from assignment parameters, not copied from core output.",
        "notes": ["S-box rows are the first and fourth bits; columns are the middle two bits.",
                  "assignment total shifts are 1 and 2; cumulative total shifts are 1 and 3.",
                  "IP inverse is applied only after the second round; no swap follows the second round."],
        "vectors": vectors,
    }
    write_json(out / "hand_vectors.json", data)
    return data


def cross_vectors(out):
    rows = []
    for schedule in SCHEDULES:
        for key in (0, 1, 255, 256, 512, KEY, 1022, 1023):
            for plain in (0, 1, 15, 85, 127, PLAIN, 170, 255):
                first, second = reference.generate_subkeys_bits(f"{key:010b}", schedule)
                cipher = reference.encrypt_bits(f"{plain:08b}", f"{key:010b}", schedule)
                assert sdes.encrypt_block(plain, key, schedule) == int(cipher, 2)
                assert sdes.decrypt_block(int(cipher, 2), key, schedule) == plain
                assert reference.decrypt_bits(cipher, f"{key:010b}", schedule) == f"{plain:08b}"
                rows.append({"schedule": schedule, "key_bits": f"{key:010b}", "plaintext_bits": f"{plain:08b}",
                             "ciphertext_bits": cipher, "k1_bits": first, "k2_bits": second})
    write_json(out / "cross_vectors.json", {"format": "sdes-cross-vectors-v1", "scope": "two independent local implementations",
                                             "external_group_test_status": "not_performed_no_other_group_program_or_results_supplied",
                                             "vectors": rows})
    with (out / "cross_vectors.csv").open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    return {"exchange_vectors": len(rows), "external_group_test_status": "not_performed", "independent_local_cross_check": "passed",
            "exhaustive_cases_per_schedule": 1024 * 256, "total_exhaustive_cases": 2 * 1024 * 256,
            "checks_each_case": ["core encryption equals independent string-reference encryption",
                                 "core decrypts reference ciphertext to original plaintext",
                                 "reference decrypts core ciphertext to original plaintext"],
            "fixed_key_bijections_per_schedule": 1024}


def ascii_evidence(out):
    rows = []
    texts = {"empty": "", "control_characters": "\0\t\n\r\x1b\x7f", "normal": "Hello S-DES!",
             "all_ascii_0_to_127": "".join(chr(value) for value in range(128))}
    for schedule in SCHEDULES:
        for name, text in texts.items():
            cipher = sdes.encrypt_ascii(text, KEY, schedule)
            decoded = sdes.decrypt_ascii(cipher, KEY, schedule)
            assert decoded == text
            assert reference.encrypt_ascii(text, KEY, schedule) == cipher
            assert reference.decrypt_ascii(cipher, KEY, schedule) == text
            rows.append({"schedule": schedule, "name": name, "plaintext_repr": repr(text),
                         "plaintext_hex": text.encode("ascii").hex(), "byte_length": len(cipher),
                         "ciphertext_hex": cipher.hex(), "ciphertext_bytes": list(cipher),
                         "decrypted_repr": repr(decoded), "round_trip": True, "independent_agreement": True})
        data = bytes(range(256))
        cipher = sdes.encrypt_bytes(data, KEY, schedule)
        assert reference.encrypt_bytes(data, KEY, schedule) == cipher
        assert sdes.decrypt_bytes(cipher, KEY, schedule) == data
        assert reference.decrypt_bytes(cipher, KEY, schedule) == data
        rows.append({"schedule": schedule, "name": "all_bytes_0_to_255", "byte_length": 256,
                     "plaintext_hex": data.hex(), "ciphertext_hex": cipher.hex(), "round_trip": True, "independent_agreement": True})
    rejected = []
    for text in ("中文", "é", "🙂", "ASCII\u0080"):
        try:
            sdes.encrypt_ascii(text, KEY)
        except UnicodeEncodeError as error:
            rejected.append({"input_repr": repr(text), "error_type": type(error).__name__, "rejected": True})
        else:
            raise AssertionError("Non-ASCII text was unexpectedly accepted")
    data = {"key_bits": f"{KEY:010b}", "mode": "independent 8-bit blocks, no padding", "cases": rows, "non_ascii_rejections": rejected}
    write_json(out / "ascii_vectors.json", data)
    return {"cases": len(rows), "all_128_ascii_verified": True, "all_256_bytes_verified": True, "non_ascii_rejections": len(rejected)}


def brute_evidence(out, schedule):
    # This first pair admits several non-equivalent keys, so adding the hand
    # vector demonstrates actual filtering as well as the surviving equivalents.
    plain_values = (0b11010111, PLAIN, 0, 255, 85, 170)
    pairs = [(plain, int(reference.encrypt_bits(f"{plain:08b}", f"{KEY:010b}", schedule), 2)) for plain in plain_values]
    runs = []
    for count in range(1, len(pairs) + 1):
        events = []
        result = analysis_tools.brute_force(pairs[:count], schedule, progress=lambda *event: events.append(event))
        expected = [key for key in range(1024) if all(reference.encrypt_block(p, key, schedule) == c for p, c in pairs[:count])]
        assert result["candidate_keys"] == expected
        assert KEY in result["candidate_keys"]
        assert events[0][0] == 0 and events[-1][0] == 1024 and len(events) == 1025
        result["independent_reference_candidates_match"] = True
        result["contains_original_key"] = True
        result["progress_events"] = len(events)
        result["progress_first"] = list(events[0])
        result["progress_last"] = list(events[-1])
        runs.append(result)
    write_json(out / f"brute_force_{schedule}.json", {"original_key": f"{KEY:010b}", "schedule": schedule,
               "timing_method": "time.perf_counter, wall timestamps local ISO 8601 with timezone",
               "runs": runs, "final_key_is_unique": runs[-1]["candidate_count"] == 1,
               "interpretation": "Every candidate is reported. More than one candidate is not a uniquely recovered key."})
    return {"single_pair_candidate_count": runs[0]["candidate_count"], "multiple_pair_candidate_count": runs[-1]["candidate_count"],
            "single_pair_candidates": runs[0]["candidate_key_bits"], "multiple_pair_candidates": runs[-1]["candidate_key_bits"],
            "candidate_counts_by_pair_count": [run["candidate_count"] for run in runs],
            "elapsed_seconds_by_pair_count": [run["elapsed_seconds"] for run in runs], "contains_original_key": True}


def collision_evidence(out, schedule):
    scan = analysis_tools.scan_all_plaintexts(schedule)
    equivalent = analysis_tools.equivalent_key_analysis(schedule)
    mapping = bytes(sdes.encrypt_block(plain, key, schedule) for key in range(1024) for plain in range(256))
    mapping_path = out / f"full_mapping_{schedule}.bin"
    mapping_path.write_bytes(mapping)
    signatures = {}
    for key in range(1024):
        signatures.setdefault(mapping[key * 256:(key + 1) * 256], []).append(key)
    expected_classes = sorted(signatures.values(), key=lambda keys: keys[0])
    assert expected_classes == [group["keys"] for group in equivalent["equivalence_groups"]]
    assert all(len(set(signature)) == 256 for signature in signatures)
    # Independently count buckets from the saved complete mapping, then compare
    # with analysis_tools' actual per-plaintext output.
    for plain, row in enumerate(scan["plaintexts"]):
        counts = [0] * 256
        for key in range(1024):
            counts[mapping[key * 256 + plain]] += 1
        assert row["distinct_ciphertexts"] == sum(count > 0 for count in counts)
        assert row["max_bucket_size"] == max(counts)
        assert row["collision_buckets"] == sum(count > 1 for count in counts)
        assert row["collision_key_pairs"] == sum(count * (count - 1) // 2 for count in counts)
    write_json(out / f"collision_scan_{schedule}.json", scan)
    with (out / f"collision_scan_{schedule}.csv").open("w", encoding="utf-8", newline="") as stream:
        fields = ("plaintext", "plaintext_int", "distinct_ciphertexts", "max_bucket_size", "collision_buckets", "collision_key_pairs", "empty_buckets", "min_bucket_size")
        writer = csv.DictWriter(stream, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(scan["plaintexts"])
    write_json(out / f"equivalent_keys_{schedule}.json", equivalent)
    fixed = analysis_tools.collision_analysis(PLAIN, schedule)
    write_json(out / f"collision_buckets_{schedule}.json", fixed)
    # Deliberately find a same-output pair that is NOT globally equivalent.
    witness = None
    for group in fixed["groups"]:
        for first_index, key1 in enumerate(group["keys"]):
            for key2 in group["keys"][first_index + 1:]:
                signature1 = mapping[key1 * 256:(key1 + 1) * 256]
                signature2 = mapping[key2 * 256:(key2 + 1) * 256]
                if signature1 != signature2:
                    different_plain = next(p for p in range(256) if signature1[p] != signature2[p])
                    witness = {"collision_plaintext": f"{PLAIN:08b}", "same_ciphertext": group["ciphertext"],
                               "key1": f"{key1:010b}", "key2": f"{key2:010b}", "globally_equivalent": False,
                               "distinguishing_plaintext": f"{different_plain:08b}",
                               "key1_distinguishing_ciphertext": f"{signature1[different_plain]:08b}",
                               "key2_distinguishing_ciphertext": f"{signature2[different_plain]:08b}"}
                    break
            if witness:
                break
        if witness:
            break
    assert witness is not None
    example = {
        "schedule": schedule, "non_equivalent_collision_example": witness,
        "globally_equivalent_example": equivalent["equivalent_groups"][0] if equivalent["equivalent_groups"] else None,
        "pigeonhole_explanation": "For any fixed 8-bit plaintext, 1024 keys map into at most 256 ciphertexts. Therefore some ciphertext has at least ceil(1024/256)=4 keys, and collisions are unavoidable. This does not prove that those keys agree on every plaintext.",
        "global_equivalence_criterion": "Two keys are globally equivalent here iff all 256 entries of their complete encryption permutations agree.",
        "full_mapping": {"file": mapping_path.name, "shape": [1024, 256], "dtype": "unsigned byte",
                         "offset_formula": "key * 256 + plaintext", "sha256": sha256(mapping_path)},
    }
    write_json(out / f"collision_examples_{schedule}.json", example)
    return {"plaintexts_scanned": 256, "keys_each": 1024, "encryptions": 262144,
            "min_distinct_ciphertexts": scan["min_distinct_ciphertexts"], "max_distinct_ciphertexts": scan["max_distinct_ciphertexts"],
            "largest_bucket_size": scan["largest_bucket_size"], "all_plaintexts_have_collisions": scan["all_plaintexts_have_collisions"],
            "distinct_permutations": equivalent["distinct_permutations"], "equivalent_group_count": equivalent["equivalent_group_count"],
            "largest_equivalence_group": equivalent["largest_equivalence_group"], "scan_elapsed_seconds": scan["elapsed_seconds"],
            "equivalence_elapsed_seconds": equivalent["elapsed_seconds"], "non_equivalent_collision_example": witness}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "results")
    args = parser.parse_args()
    out = args.output.resolve()
    out.mkdir(parents=True, exist_ok=True)
    started_at = timestamp()
    start = perf_counter()
    tests = run_tests(out)
    hand_vectors(out)
    cross = cross_vectors(out)
    ascii_summary = ascii_evidence(out)
    schedule_results = {}
    for schedule in SCHEDULES:
        brute = brute_evidence(out, schedule)
        collisions = collision_evidence(out, schedule)
        schedule_results[schedule] = {"brute_force": brute, "collisions": collisions}
        print(f"{schedule}: candidates {brute['candidate_counts_by_pair_count']}; distinct permutations {collisions['distinct_permutations']}", flush=True)
    summary = {
        "schema": "sdes-experiment1-evidence-v1", "started_at": started_at, "finished_at": timestamp(),
        "elapsed_seconds": perf_counter() - start, "primary_schedule": "assignment",
        "schedule_definitions": {"assignment": {"total_half_shifts": [1, 2]}, "cumulative": {"total_half_shifts": [1, 3]}},
        "parameters": {"P10": list(reference.P10), "P8": list(reference.P8), "IP": list(reference.IP),
                       "IP_inverse": list(reference.IP_INVERSE), "EP": list(reference.EXPANSION), "P4": list(reference.P4),
                       "SBOX1": reference.LEFT_BOX, "SBOX2": reference.RIGHT_BOX},
        "environment": {"python": sys.version, "executable": sys.executable, "platform": platform.platform(),
                        "implementation": platform.python_implementation(), "cwd": str(ROOT)},
        "source_sha256": {name: sha256(ROOT / name) for name in ("sdes.py", "analysis_tools.py", "reference_sdes.py",
                          "scripts/run_evidence.py", "scripts/compare_cross_vectors.py", "tests/test_sdes.py",
                          "tests/test_analysis_tools.py", "tests/test_exchange.py")},
        "unit_tests": tests,
        "stage1_basic": {"hand_vectors_passed": True, "exhaustive_assignment_pairs": 262144,
                         "fixed_key_bijections_verified": 1024, "invalid_inputs_rejected": True,
                         "gui_evidence": "See separate GUI screenshots and screenshot manifest generated by scripts/capture_gui.py."},
        "stage2_cross_implementation": cross,
        "stage3_ascii": ascii_summary,
        "schedule_results": schedule_results,
        "limitations": ["Actual testing with another student group's independent program has not been performed; no such program/results were supplied.",
                        "GUI screenshots must be reviewed separately; computational tests do not prove GUI appearance or every interaction.",
                        "cumulative is a compatibility schedule; primary assignment conclusions use total shifts 1 and 2.",
                        "S-DES is a small teaching cipher. Independent byte mode reveals repeated bytes and is not suitable for protecting real information."],
    }
    write_json(out / "summary.json", summary)
    artifacts = {path.name: {"size_bytes": path.stat().st_size, "sha256": sha256(path)}
                 for path in sorted(out.iterdir()) if path.is_file() and path.name != "evidence_manifest.json"}
    write_json(out / "evidence_manifest.json", {"created_at": timestamp(), "generator": "scripts/run_evidence.py", "files": artifacts})
    print(f"Evidence saved to {out}", flush=True)


if __name__ == "__main__":
    main()
